name: cuidador_app
description: Aplicativo de suporte Ã  dor por osteoartrite
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9

  provider: ^6.1.1
  shared_preferences: ^2.2.2

  http: ^1.2.0
  dio: ^5.4.0

  fl_chart: ^0.69.0

  flutter_form_builder: ^9.1.1

  intl: any  

  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2

  flutter_tts: ^3.8.5

  sqflite: ^2.3.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/corpofem.png
    - assets/corpomasc.png


